domain_path: /home/joseph/Documents/vivado/avnet-zuboard-experiments/zuboard-projects/P2_PS_PL_RGB/vitis/ps_pl_rgb_platform/export/ps_pl_rgb_platform/sw/standalone_psu_cortexa53_0
app_src_dir: /home/joseph/Vitis/2024.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
